RockinMilla/FtcRobotController

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> LearnBranching

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> AddMeaninglessComment

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> FirstCHMNPractice

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> ResolveWarnings

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> MakeAutonomousMethods

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> AddFunction

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> AutoTurnToAngle

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> ImproveTurnToHeading

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> ServoProgram

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> TurnToLine

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> Fix the 1-button turning and set the wheels to BRAKE when there is no power.

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> Add instructions for neha

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> CodeOrganization

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
- TeamCode/src/main/res/xml/wheelsandclaw.xml
> ViperSafety

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> AdviceFromJ

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> J Vertical hold advice.

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> Fix-Viper-Slide

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorLimelight3A.java
> LimeCamera

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> Milla'sTuesdayCode

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> JNotesToMilla

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> CallieOct10

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorLimelight3A.java
> NewProgramNames

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> JTestingRandomStuff

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> Callie-10/13

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SensorLimelight3A.java
> NehaAprilTagTest

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
- exportToHTML/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java.html
> NehaUpdated

- FtcRobotController/src/main/AndroidManifest.xml
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptAprilTagLocalization.java
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptVisionColorLocator.java
- FtcRobotController/src/main/java/org/firstinspires/ftc/robotcontroller/external/samples/ConceptVisionColorSensor.java
- README.md
- build.dependencies.gradle
> Update to 10.1

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> Milla-nov-1

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> Competition

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> AutoEfficiency

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/BasicOmniOpMode_Linear.java
> TeleOpSync

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> Milla-11/11

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RobotAutoDriveByTime_Linear.java
> Claw-fixes-11/14

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> YourMother

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
> FrogsRule19

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> NostrilHair20

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> WeaselSpit21

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> Testing ideas.

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> MyApolocheese22

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> Competition24

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> AllOrangeCatsShareOneBraincell26

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> WhatTheSigma27

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> Thornksgiving

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> KermitTheFrog29

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/PARKAuto.java
> Callie-11/30

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> SirGeraldisonMcGeraldimus2

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> HonHonHonCroissant

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
> increaseClawSpeeds

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
> hamburgers11

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
> Competition14

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
> ErMahGerd16

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OTOSAutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
> ohmynoodles

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ServoAdjustments.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/WristRemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/WristServoAdjustments.java
> disable-programs

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> birdIsTheWord24

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> EHHHHHHMACARENA3

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/2024IntoTheDeep/WristRemoteControl24.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/NewRemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/WristRemoteControl.java
> Configuration file test.

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/2024IntoTheDeep/PARKAuto.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/2024IntoTheDeep/SurvivorCode.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/2024IntoTheDeep/WristOTOSAutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/2024IntoTheDeep/WristRemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/2024IntoTheDeep/WristServoAdjustments.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
> No errors or warnings but hasn't been tested

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> Causes nullPointerException on control hub; otherwise good

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> Autonomous cannot move anything on robot; otherwise good

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> Working on installing roadrunner for deadwheels

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDrive.java
> THIS WORKS!!!

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControl.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> This perhaps works

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDrive.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RemoteControlShooter.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> This (mostly) works for now!

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDrive.java
> This works!

- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDriveBlue.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/AutoDriveRed.java
- TeamCode/src/main/java/org/firstinspires/ftc/teamcode/RockinBot.java
> This almost works!
